#define UCSRA     *(( volatile u8*)0x2B )
#define UCSRN    *(( volatile u8*)0x2A )
#define UDR     *(( volatile u8*) 0x2C)
#define UBRRL     *(( volatile u8*)0X29 )
#define UBRRH    *(( volatile u8*)0X40 )
#define      *(( volatile u8*) )